version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: eventDrivenProgramming-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: event-driven-programming
    ports:
      - "5432:5432"